### PR TITLE
"N random answers"

### PR DESCRIPTION
**Pull request by XiRouz**
Good day, dear developers.

First of all, I would like to thank you for your plugin, we have used it in our Moodle and it really helps with some tricky cases in tests.
A couple days ago my colleague asked me to implement a new mode for this question type. His user case follows: some questions have a large pool of answers, and when a teacher doesn't want to choose correct and incorrect answers precisely and manually, he needs a constant value, which can be used to hard set the amount of answers that will be present in quiz attempt.
This concept can be further refactored to use the interval between chosen constant and a minimum (2 answers).

Some teachers can find this feature useful too, so here is my pull request.

Thank you!

### CODE REVIEW

**Comment by rezeau** [comment]
@XiRouz Thanks for suggesting this new feature. I have briefly tested it and it seems to be working fine. I will do some more testing, especially checking that existing questions are correctly upgraded to your new version. I expect to merge your PR very soon.

**Comment by rezeau** [comment]
I have now tested with upgrading existing questions of type answersselect : pass
tested against [moodle-qformat_gift_answersselect](https://github.com/rezeau/moodle-qformat_gift_answersselect) pass
and 
[moodle-qformat_answersselect](https://github.com/rezeau/moodle-qformat_answersselect) pass
Thanks for a thorough-full and useful PR. I am pleased to merge it now and will promptly update my question type on the Moodle plugins repository.

**Comment by rezeau** [comment]
@XiRouz Upon further testing I've found that the 'N random answers' does not work as expected. When viewing a question in the Preview question window and pressing Starting again, the number of answers that are displayed _does not systematically correspond_ to the 'N answers in question' number selected when editing the question!
I merged too soon...
Please can you re-test and create a new PR to fix your original PR?

**Comment by XiRouz** [comment]
@rezeau Hello! While testing the question and pressing "Start again" button, I didn't detect any not expected behaviour. In my case, I have 7 answers, 3 of which are correct, and my N parameter is 4. I get 4 answers everytime I "start again" the question, the ration of correct\incorrect answers varies, as expected (1\3; 2\2; 3\1). Could you provide more details about the issue you found out?

**Comment by rezeau** [comment]
@XiRouz Thanks for responding. The unexpected number of total answers behaviour is quite erratic, sometimes it does not happen, sometimes it happens. I suggest _we keep things as they are for the time being_ and wait for more users to test it.
Thanks again for adding this option to the answersselect question type!

**Pull request merged**
